[algokit]
min_version = "v2.0.0"

[project]
type = "sdk"
name = 'reti-fast-sdk'
artifacts = "src/"

[project.run]
build = { commands = ['npm run build'], description = 'Build SDK' }
test = { commands = [
  'npm run test',
], description = 'Run smart contract tests using vitest' }
